name: _
publish_to: none

environment:
  sdk: '^3.8.0'

workspace:
  - the_delivery_app_client
  - the_delivery_app_server
  - the_delivery_app_flutter
dependency_overrides:
  flutter_secure_storage: ^10.0.0

