services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: the_delivery_app
      POSTGRES_PASSWORD: "qCxrveH3c60vgSB9KMWEWyW1usVeIVI9"
    volumes:
      - the_delivery_app_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "C80opAk3-Pb8KzMU5f3GAZllUaBpqLT0"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: the_delivery_app_test
      POSTGRES_PASSWORD: "PXOON4XWszCjYZh8HSKSRjs3kSBPuwul"
    volumes:
      - the_delivery_app_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "z7TnYZcxSkQPGYOE6ZS1lyXga8OHtCzT"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  the_delivery_app_data:
  the_delivery_app_test_data:
