shared:
  database: qCxrveH3c60vgSB9KMWEWyW1usVeIVI9
  serviceSecret: my_development_service_secret_12345
  jwtRefreshTokenHashPepper: my_development_jwt_pepper_12345
  jwtHmacSha512PrivateKey: WMMqjw85XqDVa1CMno2zb42Njm0xN43GlpnHQv9vbqn61fwsKW+08j4goDAEfwrsTMNPcKKqFkNL0K3yTkK8mA==
  emailSecretHashPepper: my_development_email_hash_pepper_12345
