name: Analyze

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.3.1'

    steps:
      - uses: actions/checkout@v4

      # Use Flutter so Flutter deps don't explode if anything touches them
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Install dependencies (server)
        working-directory: the_delivery_app_server
        run: dart pub get

      - name: Install Serverpod CLI
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: the_delivery_app_server
        run: serverpod generate

      - name: Analyze (server)
        working-directory: the_delivery_app_server
        run: dart analyze --fatal-infos